services:
  - type: web
    name: text-extraction-service
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: '8000'
